data: 
  root: 'data/CycPeptMPDB/'   # data folder, contain two files: train.csv and val.csv
  batch_size: 128                    # 
  num_workers: 4                    # number of workers for data loading
  feat_names: 'smi_img'             # smi_img
  target_col: 'score'

  metis:
    n_patches: 32
    enable: true  # Enable Metis partition (otherwise use random partition)
    online: true    # Enable data augmentation
    n_patches: 32    # The number of partitions
    drop_rate: 0.3    # Whether to randomly drop a set of edges before each metis partition
    num_hops: 1    # expanding patches with k hop neighbourhood

  pos_enc:
    rw_dim: 16  # Random walk structural encoding
    lap_dim: 0  # Laplacian eigenvectors positional encoding
    patch_rw_dim: 8  # Patch random walk structural encoding
    patch_num_diff: -1  # Patch PE diffusion steps


device: 0
seed: null
logfile: null

model:
  molcl:
    enc_width: 2048
    proj_dim: 256
    temp_scale: 0.07

  hidden_size: 128
  nlayer_gnn: 4
  nlayer_mlpmixer: 2
  gMHA_type: MLPMixer
  gnn_type: GINEConv
  pool: 'mean'
  residual: true
  dropout: 0.
  mlpmixer_dropout: 0.5
  pos_enc:
    rw_dim: 16  # Random walk structural encoding
    lap_dim: 0  # Laplacian eigenvectors positional encoding
    patch_rw_dim: 8  # Patch random walk structural encoding
    patch_num_diff: -1  # Patch PE diffusion steps


train:  # Training params
  device: 'cuda'                    # device to use for training
  max_epochs: 1000                  # *total number of epochs, 200
  use_amp: true                     # whether to use torch.amp for automatic mixed precision training
  task_type: regression             # task type, 'classification' or 'regression'
  learning_rate: 0.001              # *learning rate
  lr_patience: 20
  lr_decay: 0.5
  min_lr: 1e-5
  weight_decay: 0.
