data: 
  batch_size: 128              # batch size
  num_workers: 4               # number of workers for data loading
  pos_enc_wavelet:
    is_undirected: true
    dim: 8

  dataset_name: 'cycpeptmpdb'
  root: 'data/kras/'   # data folder, contain two files: train.csv and val.csv
  smiles_col: 'smi'           # smi
  # target_col: 'is_cpp'
  target_col: 'score'

model:
  device: cuda:1
  pe_name: wave
  num_layer: 2
  num_head: 4
  norm: batch
  emb_dim: 84
  num_task: 1
  dropout: 0.25
  residual: 1
  num_cluster: 10
  attn_dropout: 0.5
  local_gnn_type: CustomGatedGCN
  global_model_type: Transformer
  pos_dim: 8
  version: custom
  gnn_type: gine # only used for MGT (not CustomMGT)
  seed: 1

train:  # Training params
  device: 'cuda:1'                    # device to use for training
  max_epochs: 200                  # *total number of epochs, 200
  task_type: regression             # task type, 'classification' or 'regression'
  learning_rate: 0.001              # *learning rate
  lr_patience: 10
  lr_decay: 0.5
  min_lr: 1e-6
  weight_decay: 0.
