data: 
  type: 'bpe'                    # data type, 'smiles' or 'helm' or 'aa_seq'
  input_path: 'data/CycPeptMPDB/'        # pretrain data folder, contain two files: train.csv and val.csv
  col_name: 'helm,score'                  
  max_len: 40                       # *max length after tokenization, set a smaller number (rf. max_position_embeddings) to reduce memory usage
  batch_size: 60                   
  num_workers: 2                    # number of workers for data loading
  bpe_path: 'results/helm_bpe'      # path to save bpe model

model:  # Model params
  model_type: 'bert'                # 'siamese' or 'bert'
  output_size: 1                    # output size of the model
  bert:
    context_length: 256             # default 600
    width: 256
    n_heads: 8
    n_layers: 6
    mlm_probability: 0.15           # masked probability in mlm

train:  # Training params
  max_epochs: 10000                    # *total number of epochs
  learning_rate: 0.0004             # *learning rate
  device: 'cuda'                    # device to use for training
  use_amp: true                     # whether to use torch.amp for automatic mixed precision training
  distributed: true                 # whether to use distributed training
