data: 
  input_path: 'data/CycPeptMPDB/'   # data folder, contain two files: train.csv and val.csv
  batch_size: 240                   
  num_workers: 4                    # number of workers for data loading
  feat_names: 'smi_img'                 #'fps,monomer_dps,smi_bert,2dps'
  target_col: 'score'

train:  # Training params
  max_epochs: 1000                  # *total number of epochs
  learning_rate: 0.005              # *learning rate
  device: 'cuda'                    # device to use for training
  use_amp: false                     # whether to use torch.amp for automatic mixed precision training
  model_type: 'vit'                 # model type, 'vit' or 'fps_dps'
  distributed: true                 # whether to use distributed training
  