data: 
  input_path: 'data/CycPeptMPDB/'   # data folder, contain two files: train.csv and val.csv
  batch_size: 120                   
  num_workers: 4                    # number of workers for data loading
  feat_names: 'smi_img'             #'fps,monomer_dps,smi_bert,2dps'
  image_size: 500                   # image size for resnet
  target_col: 'score'

model:
  resnet:
    num_classes: 1                    # number of classes
    pretrained: true                 # whether to use pretrained model
    model_name: 'ResNet50'            # model name, 'ResNet18', 'ResNet50'

train:  # Training params
  max_epochs: 1000                  # *total number of epochs
  learning_rate: 0.005              # *learning rate
  device: 'cuda'                    # device to use for training
  use_amp: true                     # whether to use torch.amp for automatic mixed precision training
  model_type: 'resnet'              # model type, 'resnet' or 'fps_dps'
  distributed: true                 # whether to use distributed training
  